version: '3'

services:
    web:
        build:
            context: ./
            dockerfile: ./Dockerfile
        container_name: spaceships-backend
        volumes:
            - .:/var/www/html
            - ./default:/etc/nginx/sites-available/default
        ports:
            - "8001:80"
        depends_on:
            - db

    db:
        image: mysql:8
        container_name: spaceships-mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker/data:/var/lib/mysql
        ports:
            - "3310:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: spaceships-phpmyadmin
        ports:
            - "8090:80"
        environment:
            - PMA_HOST=db
            - MYSQL_ROOT_PASSWORD=root
        depends_on:
            - db
